version: '3.7'
services:
    api:
        build:
            context: .
            dockerfile: dev.Dockerfile
        restart: always
        environment:
            NODE_ENV: development
            PORT: 3000
            MONGO_URL: mongodb://admin:admin@db:27017/?authSource=admin
            MONGO_DATABASE_NAME: auth
            SECRET_JWT: secret
            SALT: salt
        volumes:
            - .:/usr/src/app/src
        ports:
            - '3000:3000'
